# Default configuration for CM
# This file contains the default configuration settings for the Code Manager (CM)

# Base path for code storage
# Default: $HOME/Code
base_path: ~/Code/src

# Status file path
# Default: $HOME/.cm/status.yaml
status_file: ~/.cm/status.yaml
